<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/knihovna/app/Presentation/Home/default.latte */
final class Template_d29389b1b8 extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/knihovna/app/Presentation/Home/default.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* line 1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['book' => '18'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<link rel="stylesheet" href="';
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($basePath)) /* line 2 */;
		echo '/css/style.css">
<div class="container">

    <!-- Header -->
    <header class="header">
        <h1>Welcome to Library 📚</h1>
        <p>Discover our collection of books!</p>

        <div class="top-buttons">
            <a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Users:default')) /* line 11 */;
		echo '" class="btn green">Users</a>
            <a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Book:default')) /* line 12 */;
		echo '" class="btn blue">Books</a>
        </div>
    </header>

    <!-- Seznam knih -->
    <section class="books-grid">
';
		foreach ($books as $book) /* line 18 */ {
			echo '        <div class="book-card">
            <h3>';
			echo LR\Filters::escapeHtmlText($book->title) /* line 20 */;
			echo '</h3>
';
			if (isset($book->author)) /* line 21 */ {
				echo '            <p><strong>Author:</strong> ';
				echo LR\Filters::escapeHtmlText($book->author) /* line 21 */;
				echo '</p>';
			}
			echo "\n";
			if (isset($book->year)) /* line 22 */ {
				echo '            <p><strong>Year:</strong> ';
				echo LR\Filters::escapeHtmlText($book->year) /* line 22 */;
				echo '</p>';
			}
			echo "\n";
			if (isset($book->isbn)) /* line 23 */ {
				echo '            <p><strong>ISBN:</strong> ';
				echo LR\Filters::escapeHtmlText($book->isbn) /* line 23 */;
				echo '</p>';
			}
			echo '
        </div>
';

		}

		echo '    </section>

</div>
';
	}
}
