<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/knihovna/app/Presentation/Users/templates/Users/edit.latte */
final class Template_654c95b221 extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/knihovna/app/Presentation/Users/templates/Users/edit.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<h1>';
		if (isset($user)) /* line 1 */ {
			echo 'Edit user';
		} else /* line 1 */ {
			echo 'Add user';
		}
		echo '</h1>

';
		$ʟ_tmp = $this->global->uiControl->getComponent('userForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* line 3 */;

		echo '
<p><a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Users:default')) /* line 5 */;
		echo '">Back to the list</a></p>';
	}
}
