<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/knihovna/app/Presentation/Book/templates/Book/default.latte */
final class Template_f08b4205da extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/knihovna/app/Presentation/Book/templates/Book/default.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '
    <h1>Book List</h1>
    <p><a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Users:default')) /* line 3 */;
		echo '">Back to Users</a></p>



';
		$ʟ_tmp = $this->global->uiControl->getComponent('bookForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* line 7 */;

		echo '
    <h3>List of books</h3>
    <table background-color="white" border="1" cellpadding="5" cellspacing="0">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Year of publication</th>
            <th>Genre</th>
            <th>Copies</th>
            <th>Avaliable</th>
            <th>Added</th>
            <th>Actions</th>
        </tr>

';
		foreach ($books as $b) /* line 24 */ {
			echo '            <tr>
                <td>';
			echo LR\Filters::escapeHtmlText($b->id) /* line 26 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->title) /* line 27 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->author) /* line 28 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->isbn) /* line 29 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->publication_year) /* line 30 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->genre) /* line 31 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->total_copies) /* line 32 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->available_copies) /* line 33 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText(($this->filters->date)($b->added_at, 'd.m.Y')) /* line 34 */;
			echo '</td>
                <td>
                    <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('default', ['id' => $b->id])) /* line 36 */;
			echo '">EDIT</a>
                    <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('delete!', ['id' => $b->id])) /* line 37 */;
			echo '"
                       onclick="return confirm(\'Do you really want to delete this book?\');">DELETE</a>
                </td>
            </tr>
';

		}

		echo '    </table>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['b' => '24'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
