<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/knihovna/app/Presentation/Users/templates/Users/default.latte */
final class Template_b203d64f51 extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/knihovna/app/Presentation/Users/templates/Users/default.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<h1>User list</h1>



<a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Users:default')) /* line 5 */;
		echo '">User list</a>

<p><a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Users:add')) /* line 7 */;
		echo '">Add a new user</a></p>
<p><a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Book:default')) /* line 8 */;
		echo '">List of books</a></p>



<table background-color="white" border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Created at</th>
        <th>Action</th>
    </tr>
';
		foreach ($users as $u) /* line 23 */ {
			echo '        <tr>
            <td>';
			echo LR\Filters::escapeHtmlText($u->id) /* line 25 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->username) /* line 26 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->first_name) /* line 27 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->last_name) /* line 28 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->email) /* line 29 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->role) /* line 30 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->created_at) /* line 31 */;
			echo '</td>
            <td>
                <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Users:edit', [$u->id])) /* line 33 */;
			echo '">EDIT</a>
                <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('delete!', [$u->id])) /* line 34 */;
			echo '" onclick="return confirm(\'Do you really want to delte this?\')">DELETE</a>
            </td>
        </tr>
';

		}

		echo '</table>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['u' => '23'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
